# Generated by Django 5.0.3 on 2024-03-15 09:44

import Referral_system.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Referral_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[Referral_system.models.validate_date]),
        ),
    ]
